### ISSUE TITLE
[Bug] Issues when running npm run build

### ISSUE THREAD

**Issue by hamoody347** [teamupdivision/ct-vue-soft-ui-dashboard-pro-laravel#1]
### Version
1.0.0 
### Reproduction link
https://github.com/creativetimofficial/ct-vue-soft-ui-dashboard-pro-laravel
### Operating System
Windows
### Device
Laptop
### Browser & Version
Opera
### Steps to reproduce
1. Installed the ZIP file
2. Extracted it
3. Ran npm install
4. Ran npm run build

### What is expected?
the project to actually build and create the dist file
### What is actually happening?
I am getting this error

js/chunk-vendors.6616173d.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at C:\Users\ninga\Desktop\Creative Tim Template\node_modules\terser-webpack-plugin\dist\index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\terser-webpack-plugin\dist\index.js:160:259)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\ninga\Desktop\Creative Tim Template\node_modules\webpack\lib\Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\ninga\Desktop\Creative Tim Template\node_modules\webpack\lib\Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\webpack\lib\Compilation.js:1342:27)
    at C:\Users\ninga\Desktop\Creative Tim Template\node_modules\webpack\lib\Compiler.js:675:18
    at C:\Users\ninga\Desktop\Creative Tim Template\node_modules\webpack\lib\Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\webpack\lib\Compilation.js:1253:28)
    at C:\Users\ninga\Desktop\Creative Tim Template\node_modules\webpack\lib\Compiler.js:672:17
    at _done (eval at create (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (C:\Users\ninga\Desktop\Creative Tim Template\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
    at C:\Users\ninga\Desktop\Creative Tim Template\node_modules\webpack\lib\Compilation.js:1185:12
    at C:\Users\ninga\Desktop\Creative Tim Template\node_modules\webpack\lib\Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

---

**Comment by teamupdivision** [comment]
Hello, 

Than you for using Creative TIM products!

Could you please let us know what version of Node you are using?  Could you please try with Node 16 and let us know if that fixes the issue? 

Best.
